version: '3'
services:
  app:
    build: .
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "3000:3000"
      - "8088:8088"
    volumes:
      - .:/usr/src/
      - /usr/src/node_modules
      - /usr/src/react/node_modules
      - /usr/src/express/node_modules

  postgres:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=application-monitoring-demo-db
    ports:
     - "5432:5432"
    volumes:
      - application-monitoring-demo-db:/var/lib/postgresql/data


volumes:
  application-monitoring-demo-db: